using AuthTemplateNET7.Shared.PublicModels;

namespace AuthTemplateNET7.Server.Seeding;

public class ProductsSeeder
{
    private readonly DataContext dataContext;
    private readonly Random random;

    #region json

    string json = @"[{""Name"":""Potatoes - Fingerling 4 Oz"",""Description"":""Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est."",""Price"":463,""ImgUrl"":""http://dummyimage.com/353x268.png/5fa2dd/ffffff""},
{""Name"":""Nantucket Apple Juice"",""Description"":""Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis."",""Price"":231,""ImgUrl"":""http://dummyimage.com/463x202.png/cc0000/ffffff""},
{""Name"":""Cookies - Fortune"",""Description"":""Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque."",""Price"":231,""ImgUrl"":""http://dummyimage.com/345x281.png/cc0000/ffffff""},
{""Name"":""Longos - Greek Salad"",""Description"":""Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet."",""Price"":185,""ImgUrl"":""http://dummyimage.com/471x280.png/dddddd/000000""},
{""Name"":""Appetizer - Chicken Satay"",""Description"":""Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis."",""Price"":423,""ImgUrl"":""http://dummyimage.com/331x222.png/5fa2dd/ffffff""},
{""Name"":""Lychee - Canned"",""Description"":""Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem."",""Price"":199,""ImgUrl"":""http://dummyimage.com/372x184.png/5fa2dd/ffffff""},
{""Name"":""Tea - Green"",""Description"":""Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis."",""Price"":212,""ImgUrl"":""http://dummyimage.com/385x286.png/ff4444/ffffff""},
{""Name"":""Coffee - Beans, Whole"",""Description"":""Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem."",""Price"":433,""ImgUrl"":""http://dummyimage.com/361x253.png/dddddd/000000""},
{""Name"":""Pork - Backfat"",""Description"":""Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede."",""Price"":426,""ImgUrl"":""http://dummyimage.com/334x212.png/cc0000/ffffff""},
{""Name"":""Grouper - Fresh"",""Description"":""Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris."",""Price"":268,""ImgUrl"":""http://dummyimage.com/379x174.png/dddddd/000000""},
{""Name"":""Split Peas - Yellow, Dry"",""Description"":""Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus."",""Price"":137,""ImgUrl"":""http://dummyimage.com/312x240.png/dddddd/000000""},
{""Name"":""Pasta - Bauletti, Chicken White"",""Description"":""Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus."",""Price"":474,""ImgUrl"":""http://dummyimage.com/336x157.png/ff4444/ffffff""},
{""Name"":""Grenadine"",""Description"":""Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat."",""Price"":217,""ImgUrl"":""http://dummyimage.com/358x249.png/ff4444/ffffff""},
{""Name"":""Oil - Pumpkinseed"",""Description"":""Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst."",""Price"":123,""ImgUrl"":""http://dummyimage.com/333x163.png/ff4444/ffffff""},
{""Name"":""Lettuce - Frisee"",""Description"":""Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus."",""Price"":247,""ImgUrl"":""http://dummyimage.com/356x201.png/dddddd/000000""},
{""Name"":""Veal - Round, Eye Of"",""Description"":""Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue."",""Price"":296,""ImgUrl"":""http://dummyimage.com/320x285.png/cc0000/ffffff""},
{""Name"":""Trout - Hot Smkd, Dbl Fillet"",""Description"":""In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius."",""Price"":492,""ImgUrl"":""http://dummyimage.com/343x209.png/ff4444/ffffff""},
{""Name"":""Capon - Breast, Wing On"",""Description"":""Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl."",""Price"":162,""ImgUrl"":""http://dummyimage.com/470x236.png/ff4444/ffffff""},
{""Name"":""Cattail Hearts"",""Description"":""In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum."",""Price"":412,""ImgUrl"":""http://dummyimage.com/411x200.png/5fa2dd/ffffff""},
{""Name"":""Cookie Dough - Chunky"",""Description"":""Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat."",""Price"":416,""ImgUrl"":""http://dummyimage.com/380x255.png/dddddd/000000""},
{""Name"":""Wine - Mas Chicet Rose, Vintage"",""Description"":""Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet."",""Price"":388,""ImgUrl"":""http://dummyimage.com/406x170.png/cc0000/ffffff""},
{""Name"":""Worcestershire Sauce"",""Description"":""Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis."",""Price"":395,""ImgUrl"":""http://dummyimage.com/449x243.png/ff4444/ffffff""},
{""Name"":""General Purpose Trigger"",""Description"":""Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus."",""Price"":421,""ImgUrl"":""http://dummyimage.com/353x225.png/5fa2dd/ffffff""},
{""Name"":""Soup - Campbells Mushroom"",""Description"":""Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla."",""Price"":278,""ImgUrl"":""http://dummyimage.com/487x289.png/cc0000/ffffff""},
{""Name"":""Artichoke - Bottom, Canned"",""Description"":""In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor."",""Price"":352,""ImgUrl"":""http://dummyimage.com/383x151.png/5fa2dd/ffffff""},
{""Name"":""Pasta - Orecchiette"",""Description"":""Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor."",""Price"":184,""ImgUrl"":""http://dummyimage.com/440x244.png/5fa2dd/ffffff""},
{""Name"":""Garam Marsala"",""Description"":""Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue."",""Price"":458,""ImgUrl"":""http://dummyimage.com/343x275.png/5fa2dd/ffffff""},
{""Name"":""Napkin - Dinner, White"",""Description"":""Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus."",""Price"":255,""ImgUrl"":""http://dummyimage.com/421x226.png/5fa2dd/ffffff""},
{""Name"":""Appetizer - Smoked Salmon / Dill"",""Description"":""Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio."",""Price"":248,""ImgUrl"":""http://dummyimage.com/377x205.png/5fa2dd/ffffff""},
{""Name"":""Wine - Barossa Valley Estate"",""Description"":""Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl."",""Price"":307,""ImgUrl"":""http://dummyimage.com/473x295.png/5fa2dd/ffffff""},
{""Name"":""Pork - Back Ribs"",""Description"":""Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus."",""Price"":295,""ImgUrl"":""http://dummyimage.com/484x228.png/dddddd/000000""},
{""Name"":""Lychee - Canned"",""Description"":""In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum."",""Price"":452,""ImgUrl"":""http://dummyimage.com/426x230.png/cc0000/ffffff""},
{""Name"":""Beans - Kidney, Canned"",""Description"":""Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo."",""Price"":136,""ImgUrl"":""http://dummyimage.com/374x152.png/ff4444/ffffff""},
{""Name"":""Beer - Tetleys"",""Description"":""Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla."",""Price"":348,""ImgUrl"":""http://dummyimage.com/388x254.png/dddddd/000000""},
{""Name"":""Southern Comfort"",""Description"":""Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat."",""Price"":460,""ImgUrl"":""http://dummyimage.com/392x244.png/5fa2dd/ffffff""},
{""Name"":""Silicone Parch. 16.3x24.3"",""Description"":""Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio."",""Price"":261,""ImgUrl"":""http://dummyimage.com/500x225.png/5fa2dd/ffffff""},
{""Name"":""Tea - Camomele"",""Description"":""Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus."",""Price"":459,""ImgUrl"":""http://dummyimage.com/358x275.png/5fa2dd/ffffff""},
{""Name"":""Water, Tap"",""Description"":""Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui."",""Price"":140,""ImgUrl"":""http://dummyimage.com/396x300.png/5fa2dd/ffffff""},
{""Name"":""Muffin Mix - Oatmeal"",""Description"":""Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio."",""Price"":399,""ImgUrl"":""http://dummyimage.com/348x279.png/5fa2dd/ffffff""},
{""Name"":""Longos - Grilled Veg Sandwiches"",""Description"":""Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio."",""Price"":433,""ImgUrl"":""http://dummyimage.com/336x232.png/5fa2dd/ffffff""},
{""Name"":""Wine - Domaine Boyar Royal"",""Description"":""Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est."",""Price"":268,""ImgUrl"":""http://dummyimage.com/421x173.png/cc0000/ffffff""},
{""Name"":""Chicken Giblets"",""Description"":""In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat."",""Price"":109,""ImgUrl"":""http://dummyimage.com/395x282.png/5fa2dd/ffffff""},
{""Name"":""Rambutan"",""Description"":""Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede."",""Price"":341,""ImgUrl"":""http://dummyimage.com/310x276.png/cc0000/ffffff""},
{""Name"":""Wine - Ruffino Chianti Classico"",""Description"":""Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus."",""Price"":435,""ImgUrl"":""http://dummyimage.com/434x269.png/5fa2dd/ffffff""},
{""Name"":""Shrimp - 16/20, Iqf, Shell On"",""Description"":""Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo."",""Price"":315,""ImgUrl"":""http://dummyimage.com/405x232.png/ff4444/ffffff""},
{""Name"":""Allspice - Jamaican"",""Description"":""Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem."",""Price"":332,""ImgUrl"":""http://dummyimage.com/315x216.png/ff4444/ffffff""},
{""Name"":""Alize Sunset"",""Description"":""Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor."",""Price"":140,""ImgUrl"":""http://dummyimage.com/308x275.png/ff4444/ffffff""},
{""Name"":""Oregano - Fresh"",""Description"":""Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero."",""Price"":368,""ImgUrl"":""http://dummyimage.com/303x260.png/cc0000/ffffff""},
{""Name"":""Wine - Trimbach Pinot Blanc"",""Description"":""Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero."",""Price"":131,""ImgUrl"":""http://dummyimage.com/377x215.png/5fa2dd/ffffff""},
{""Name"":""Roe - Flying Fish"",""Description"":""Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci."",""Price"":477,""ImgUrl"":""http://dummyimage.com/471x262.png/5fa2dd/ffffff""},
{""Name"":""Orange Roughy 4/6 Oz"",""Description"":""Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est."",""Price"":234,""ImgUrl"":""http://dummyimage.com/347x285.png/ff4444/ffffff""},
{""Name"":""Pike - Frozen Fillet"",""Description"":""Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices."",""Price"":284,""ImgUrl"":""http://dummyimage.com/441x235.png/dddddd/000000""},
{""Name"":""Tart - Lemon"",""Description"":""Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis."",""Price"":439,""ImgUrl"":""http://dummyimage.com/497x173.png/cc0000/ffffff""},
{""Name"":""Wine - Mas Chicet Rose, Vintage"",""Description"":""Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend."",""Price"":265,""ImgUrl"":""http://dummyimage.com/443x258.png/dddddd/000000""},
{""Name"":""Sugar - Crumb"",""Description"":""Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum."",""Price"":175,""ImgUrl"":""http://dummyimage.com/303x271.png/cc0000/ffffff""},
{""Name"":""Chef Hat 20cm"",""Description"":""In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis."",""Price"":390,""ImgUrl"":""http://dummyimage.com/478x183.png/cc0000/ffffff""},
{""Name"":""Tart Shells - Savory, 2"",""Description"":""Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst."",""Price"":454,""ImgUrl"":""http://dummyimage.com/356x209.png/ff4444/ffffff""},
{""Name"":""Chocolate - Pistoles, White"",""Description"":""Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus."",""Price"":468,""ImgUrl"":""http://dummyimage.com/310x279.png/5fa2dd/ffffff""},
{""Name"":""Muffin Chocolate Individual Wrap"",""Description"":""Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla."",""Price"":300,""ImgUrl"":""http://dummyimage.com/369x199.png/dddddd/000000""},
{""Name"":""Potatoes - Purple, Organic"",""Description"":""In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula."",""Price"":308,""ImgUrl"":""http://dummyimage.com/460x265.png/5fa2dd/ffffff""},
{""Name"":""Garbage Bags - Clear"",""Description"":""Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue."",""Price"":412,""ImgUrl"":""http://dummyimage.com/301x183.png/dddddd/000000""},
{""Name"":""Soup - Campbellschix Stew"",""Description"":""Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus."",""Price"":379,""ImgUrl"":""http://dummyimage.com/415x157.png/cc0000/ffffff""},
{""Name"":""Wiberg Cure"",""Description"":""Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus."",""Price"":162,""ImgUrl"":""http://dummyimage.com/380x291.png/5fa2dd/ffffff""},
{""Name"":""Yoplait - Strawbrasp Peac"",""Description"":""Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc."",""Price"":141,""ImgUrl"":""http://dummyimage.com/455x239.png/5fa2dd/ffffff""},
{""Name"":""Eggplant Oriental"",""Description"":""Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh."",""Price"":308,""ImgUrl"":""http://dummyimage.com/427x262.png/5fa2dd/ffffff""},
{""Name"":""Mince Meat - Filling"",""Description"":""Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque."",""Price"":306,""ImgUrl"":""http://dummyimage.com/314x194.png/dddddd/000000""},
{""Name"":""Wine - Port Late Bottled Vintage"",""Description"":""Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy."",""Price"":238,""ImgUrl"":""http://dummyimage.com/349x296.png/dddddd/000000""},
{""Name"":""Crab Brie In Phyllo"",""Description"":""Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam."",""Price"":157,""ImgUrl"":""http://dummyimage.com/389x284.png/cc0000/ffffff""},
{""Name"":""Sandwich Wrap"",""Description"":""Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla."",""Price"":270,""ImgUrl"":""http://dummyimage.com/460x272.png/dddddd/000000""},
{""Name"":""Pastry - Baked Scones - Mini"",""Description"":""Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue."",""Price"":374,""ImgUrl"":""http://dummyimage.com/344x171.png/dddddd/000000""},
{""Name"":""Juice - Cranberry 284ml"",""Description"":""Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat."",""Price"":269,""ImgUrl"":""http://dummyimage.com/378x259.png/dddddd/000000""},
{""Name"":""Coffee - Decaffeinato Coffee"",""Description"":""Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl."",""Price"":277,""ImgUrl"":""http://dummyimage.com/398x243.png/cc0000/ffffff""},
{""Name"":""Crush - Cream Soda"",""Description"":""Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet."",""Price"":457,""ImgUrl"":""http://dummyimage.com/426x286.png/5fa2dd/ffffff""},
{""Name"":""Veal - Provimi Inside"",""Description"":""Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti."",""Price"":471,""ImgUrl"":""http://dummyimage.com/484x163.png/5fa2dd/ffffff""},
{""Name"":""Taro Leaves"",""Description"":""Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est."",""Price"":386,""ImgUrl"":""http://dummyimage.com/384x150.png/dddddd/000000""},
{""Name"":""Veal - Brisket, Provimi,bnls"",""Description"":""Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede."",""Price"":181,""ImgUrl"":""http://dummyimage.com/312x173.png/cc0000/ffffff""},
{""Name"":""Oven Mitts 17 Inch"",""Description"":""Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla."",""Price"":497,""ImgUrl"":""http://dummyimage.com/397x150.png/5fa2dd/ffffff""},
{""Name"":""Soup - Campbells, Creamy"",""Description"":""Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat."",""Price"":488,""ImgUrl"":""http://dummyimage.com/396x229.png/cc0000/ffffff""},
{""Name"":""Cardamon Ground"",""Description"":""Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices."",""Price"":395,""ImgUrl"":""http://dummyimage.com/304x222.png/5fa2dd/ffffff""},
{""Name"":""Pork - Bacon, Double Smoked"",""Description"":""Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis."",""Price"":279,""ImgUrl"":""http://dummyimage.com/441x228.png/dddddd/000000""},
{""Name"":""Cheese - Montery Jack"",""Description"":""Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus."",""Price"":159,""ImgUrl"":""http://dummyimage.com/359x269.png/dddddd/000000""},
{""Name"":""Tart - Lemon"",""Description"":""Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio."",""Price"":143,""ImgUrl"":""http://dummyimage.com/349x241.png/5fa2dd/ffffff""},
{""Name"":""Wine - Zonnebloem Pinotage"",""Description"":""Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros."",""Price"":131,""ImgUrl"":""http://dummyimage.com/325x224.png/cc0000/ffffff""},
{""Name"":""Island Oasis - Mango Daiquiri"",""Description"":""Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius."",""Price"":192,""ImgUrl"":""http://dummyimage.com/314x251.png/ff4444/ffffff""},
{""Name"":""Tequila Rose Cream Liquor"",""Description"":""Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque."",""Price"":122,""ImgUrl"":""http://dummyimage.com/392x247.png/ff4444/ffffff""},
{""Name"":""Persimmons"",""Description"":""Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio."",""Price"":424,""ImgUrl"":""http://dummyimage.com/416x182.png/dddddd/000000""},
{""Name"":""Snapple - Iced Tea Peach"",""Description"":""Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum."",""Price"":416,""ImgUrl"":""http://dummyimage.com/326x221.png/ff4444/ffffff""},
{""Name"":""Huck Towels White"",""Description"":""Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia."",""Price"":361,""ImgUrl"":""http://dummyimage.com/401x266.png/dddddd/000000""},
{""Name"":""Island Oasis - Raspberry"",""Description"":""Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl."",""Price"":198,""ImgUrl"":""http://dummyimage.com/361x152.png/5fa2dd/ffffff""},
{""Name"":""Steampan - Half Size Shallow"",""Description"":""Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est."",""Price"":405,""ImgUrl"":""http://dummyimage.com/440x243.png/dddddd/000000""},
{""Name"":""Fond - Chocolate"",""Description"":""Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus."",""Price"":171,""ImgUrl"":""http://dummyimage.com/428x181.png/5fa2dd/ffffff""},
{""Name"":""Beef - Prime Rib Aaa"",""Description"":""Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat."",""Price"":197,""ImgUrl"":""http://dummyimage.com/353x185.png/5fa2dd/ffffff""},
{""Name"":""Vodka - Lemon, Absolut"",""Description"":""Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat."",""Price"":339,""ImgUrl"":""http://dummyimage.com/476x173.png/dddddd/000000""},
{""Name"":""Soho Lychee Liqueur"",""Description"":""Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus."",""Price"":354,""ImgUrl"":""http://dummyimage.com/488x289.png/cc0000/ffffff""},
{""Name"":""Ginger - Pickled"",""Description"":""Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo."",""Price"":285,""ImgUrl"":""http://dummyimage.com/478x217.png/dddddd/000000""},
{""Name"":""Cheese - Montery Jack"",""Description"":""Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst."",""Price"":204,""ImgUrl"":""http://dummyimage.com/379x286.png/5fa2dd/ffffff""},
{""Name"":""Red Snapper - Fresh, Whole"",""Description"":""Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum."",""Price"":117,""ImgUrl"":""http://dummyimage.com/495x299.png/ff4444/ffffff""},
{""Name"":""Garlic - Primerba, Paste"",""Description"":""Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl."",""Price"":401,""ImgUrl"":""http://dummyimage.com/342x181.png/5fa2dd/ffffff""},
{""Name"":""Grapes - Red"",""Description"":""Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat."",""Price"":189,""ImgUrl"":""http://dummyimage.com/313x232.png/cc0000/ffffff""},
{""Name"":""Guinea Fowl"",""Description"":""Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue."",""Price"":403,""ImgUrl"":""http://dummyimage.com/378x187.png/5fa2dd/ffffff""}]";

    #endregion

    public ProductsSeeder(DataContext dataContext, Random random)
    {
        this.dataContext = dataContext;
        this.random = random;
    }

    public List<Product> Seed(bool createSameProductsList, int min, int max)
    {
        Product[] products = json.FromJson<Product[]>();

        if(createSameProductsList)
        {

            var x = products.Take(max).ToList();

            foreach(var product in x)
            {
                bool noImage = random.Next(2) == 0;
                if (noImage) product.ImgUrl = null;
            }

            dataContext.AddRange(x);
            return x;
        }

        int productsLength = products.Length;

        int howMany = random.Next(min, max);

        Dictionary<string, Product> resultDict = new Dictionary<string, Product>(howMany);

        int addedCount = 0;
        while (addedCount < howMany)
        {
            int which = random.Next(0, productsLength);
            var chosen = products[which];

            if (resultDict.ContainsKey(chosen.Name)) continue;

            bool noImage = random.Next(2) == 0;

            if(noImage) chosen.ImgUrl = null;

            resultDict.Add(chosen.Name, chosen);
            addedCount++;
        }

        List<Product> result = resultDict.Values.ToList();

        dataContext.AddRange(result);

        return result;
    }
}
